In [1]:
cd("/Users/Nes/Desktop/Neuroscience/Parallel-Neuroscience/P2kCSDA")

In [68]:
BceroDura=readdlm("BceroDura.dat");

In [144]:
output2=readdlm("K.dat");

In [145]:
output2

128x128 Array{Float64,2}:
  7.33885  -0.5       -5.40608e16  …  NaN           NaN         
  7.3972    7.3972   NaN               -6.64614e35   -1.70141e38
  7.456     7.456      7.456           -4.38645e37   -9.22337e18
  7.51522   7.51522    7.51522        NaN           NaN         
  7.57487   7.57487    7.57487        NaN           NaN         
  7.63492   7.63492    7.63492     …   -1.70141e38   -1.70142e38
  7.69536   7.69536    7.69536         -2.55212e38   -1.70141e38
  7.75617   7.75617    7.75617        NaN           NaN         
  7.81733   7.81733    7.81733         -1.70141e38   -1.70141e38
  7.87882   7.87882    7.87882        NaN           NaN         
  7.94061   7.94061    7.94061     …   -1.70141e38   -9.22337e18
  8.00268   8.00268    8.00268        NaN           NaN         
  8.06501   8.06501    8.06501         -1.75458e38   -4.7707e-7 
  ⋮                                ⋱                            
 10.373    10.373     10.373           -1.70141e38   -7.47691e35

In [4]:
ConjuntoDeCoordenadasTotal=Array[]

0-element Array{Array{T,N},1}

In [6]:
for j=1:64,k=1:64
    push!(ConjuntoDeCoordenadasTotal,[j,k])
end

In [143]:
jmax=128
xconstante=[64,64]
Kduras=zeros(jmax,jmax);
@time for j=1:jmax
     xj=ConjuntoDeCoordenadasTotal[j]
     for k=1:j
            xk=ConjuntoDeCoordenadasTotal[k]
        for l=1:jmax
            xl=ConjuntoDeCoordenadasTotal[l]
            Kduras[j,k] += BceroDura[xj...]#BceroDura[(xk-xl+xconstante)...]*BceroDura[(xj-xl+xconstante)...]
            end
    end
end

  1.329613 seconds (7.41 M allocations: 258.512 MB, 2.82% gc time)


In [36]:
Kduras[128,1]

91890.6914197124

In [113]:
Kduras[1,1]-output2[1,1]

-36270.35728002549

In [110]:
output2[20,20]

541108.0

In [87]:
[ceil(8935/127),8935%127]

2-element Array{Float64,1}:
 71.0
 45.0

In [90]:
BceroDura[71,45]

31.674940257859276

In [146]:
Kduras

128x128 Array{Float64,2}:
  7.33885   0.0       0.0      …   0.0      0.0      0.0      0.0   
  7.3972    7.3972    0.0          0.0      0.0      0.0      0.0   
  7.456     7.456     7.456        0.0      0.0      0.0      0.0   
  7.51522   7.51522   7.51522      0.0      0.0      0.0      0.0   
  7.57487   7.57487   7.57487      0.0      0.0      0.0      0.0   
  7.63492   7.63492   7.63492  …   0.0      0.0      0.0      0.0   
  7.69536   7.69536   7.69536      0.0      0.0      0.0      0.0   
  7.75617   7.75617   7.75617      0.0      0.0      0.0      0.0   
  7.81733   7.81733   7.81733      0.0      0.0      0.0      0.0   
  7.87882   7.87882   7.87882      0.0      0.0      0.0      0.0   
  7.94061   7.94061   7.94061  …   0.0      0.0      0.0      0.0   
  8.00268   8.00268   8.00268      0.0      0.0      0.0      0.0   
  8.06501   8.06501   8.06501      0.0      0.0      0.0      0.0   
  ⋮                            ⋱            ⋮                       
 10.373 

In [148]:
output2

128x128 Array{Float64,2}:
  7.33885  -0.5       -5.40608e16  …  NaN           NaN         
  7.3972    7.3972   NaN               -6.64614e35   -1.70141e38
  7.456     7.456      7.456           -4.38645e37   -9.22337e18
  7.51522   7.51522    7.51522        NaN           NaN         
  7.57487   7.57487    7.57487        NaN           NaN         
  7.63492   7.63492    7.63492     …   -1.70141e38   -1.70142e38
  7.69536   7.69536    7.69536         -2.55212e38   -1.70141e38
  7.75617   7.75617    7.75617        NaN           NaN         
  7.81733   7.81733    7.81733         -1.70141e38   -1.70141e38
  7.87882   7.87882    7.87882        NaN           NaN         
  7.94061   7.94061    7.94061     …   -1.70141e38   -9.22337e18
  8.00268   8.00268    8.00268        NaN           NaN         
  8.06501   8.06501    8.06501         -1.75458e38   -4.7707e-7 
  ⋮                                ⋱                            
 10.373    10.373     10.373           -1.70141e38   -7.47691e35

In [132]:
ConjuntoDeCoordenadasTotal

4096-element Array{Array{T,N},1}:
 [1,1]  
 [1,2]  
 [1,3]  
 [1,4]  
 [1,5]  
 [1,6]  
 [1,7]  
 [1,8]  
 [1,9]  
 [1,10] 
 [1,11] 
 [1,12] 
 [1,13] 
 ⋮      
 [64,53]
 [64,54]
 [64,55]
 [64,56]
 [64,57]
 [64,58]
 [64,59]
 [64,60]
 [64,61]
 [64,62]
 [64,63]
 [64,64]