In [1]:
cd("/Users/Nes/Desktop/Neuroscience/Parallel-Neuroscience/P2kCSDA")

In [49]:
BceroDura=readdlm("BceroDura.dat");

In [50]:
output=readdlm("K.dat");

In [51]:
output

128x128 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.

In [4]:
ConjuntoDeCoordenadasTotal=Array[]

0-element Array{Array{T,N},1}

In [6]:
for j=1:64,k=1:64
    push!(ConjuntoDeCoordenadasTotal,[j,k])
end

In [7]:
jmax=128
xconstante=[64,64]
Kduras=zeros(jmax,jmax);
@time for j=1:jmax
     xj=ConjuntoDeCoordenadasTotal[j]
     for k=1:j
            xk=ConjuntoDeCoordenadasTotal[k]
        for l=1:jmax
            xl=ConjuntoDeCoordenadasTotal[l]
            Kduras[j,k]+=BceroDura[(xk-xl+xconstante)...]*BceroDura[(xj-xl+xconstante)...]
            end
    end
end

  3.460413 seconds (25.40 M allocations: 920.512 MB, 2.46% gc time)


In [36]:
Kduras[128,1]

91890.6914197124

In [20]:
Kduras - BceroDura2

128x128 Array{Float64,2}:
     2.88217e5       0.0        …      0.0        0.0            0.0
     3.05887e5       3.24116e5         0.0        0.0            0.0
     3.19989e5       3.40751e5         0.0        0.0            0.0
     3.31732e5       3.52932e5         0.0        0.0            0.0
     3.38803e5       3.62182e5         0.0        0.0            0.0
     3.42415e5       3.65804e5  …      0.0        0.0            0.0
     3.41301e5       3.66275e5         0.0        0.0            0.0
     3.38046e5       3.62402e5         0.0        0.0            0.0
     3.31926e5       3.57133e5         0.0        0.0            0.0
     3.25102e5  349053.0               0.0        0.0            0.0
     3.16711e5       3.4088e5   …      0.0        0.0            0.0
     3.08502e5       3.31003e5         0.0        0.0            0.0
     2.99495e5       3.21876e5         0.0        0.0            0.0
     ⋮                          ⋱      ⋮                            
 95745.4